const passport = require('passport');
const googleStrategy = require('passport-google-oauth20').Strategy;
const mongoose = require('mongoose');
const keys = require('../config/keys');

const users = mongoose.model('user');

/* in passport.serializeUser function
* user is exactly the same we pulled out of database in the callback function of 
* passport.use i.e the argument in done existisngUser and done user are exactly the same
* as user here in serializeUser.*/
passport.serializeUser((user, done) => {
  /* first argument is the error and it is null null
  * second argument - user.id is the unique id generated by mongo and not the googleId
  * reason for using mongo generated unique id because there may be other authentication strategy
  * like facebook, linkedId, so googleId availablity is not there *
  * thus eveything may not have googleId but have the mongo auto-generated unique Id*/
  done(null, user.id);
});
//for getting google user info like its id and store in it mongodb
passport.use(
  new googleStrategy(
    {
      clientID: keys.googleClientId,
      clientSecret: keys.googleClientSecret,
      callbackURL: '/auth/google/callback'
    },
    (accessToken, refreshToken, profile, done) => {
      //to find if the user with profle.id exist in mondodb or not
      users.findOne({ googleId: profile.id }).then(existingUser => {
        if (existingUser) {
          //already have a record with this userID, no need to create a new one
          done(null, existingUser); // to tell the passportjs that the user is there and it should resume the auth process
        } else {
          //no record with this userID, need to make a new one
          new users({ googleId: profile.id })
            .save() //to make and save recored with userID: existingUser
            .then(user => done(null, user)); //to tell the passportjs that the user is created and it should resume the auth process
        }
      });
    }
  )
);
